#!/bin/sh
echo "  ╔═══════════════════════════════╗"
echo "  ║   AI Audio Generator & DL     ║"
echo "  ╠═══════════════════════════════╣"
echo "  ║   ╭─────────╮                 ║"
echo "  ║   │  AI ⚡  │    ♫ ♪ ♫       ║"
echo "  ║   │  ┌───┐  │   ╱ ╲           ║"
echo "  ║   │  │ ▲ │  │  │MP3│          ║"
echo "  ║   │  └───┘  │   ╲ ╱           ║"
echo "  ║   ╰─────────╯    ▼▼▼          ║"
echo "  ║      ~~~~                    ║"
echo "  ║     /    \\   [DOWNLOAD]      ║"
echo "  ║    / AI   \\                  ║"
echo "  ║   /_______\\                  ║"
echo "  ║  ◉ Audio Synth v1.0          ║"
echo "  ╚═══════════════════════════════╝"
